version: '3'
services:
  deadbot:
    image: ghcr.io/deadlock_wiki/deadbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # runtime config
      DECOMPILE: true
      PARSE: true
      BOT_PUSH: false
      OUTPUT_DIR: "/output"
      CLEANUP: true
      # volumes:
      # - 'C:\Program Files (x86)\Steam\steamapps\common\Deadlock':'/data'
      # - "/mnt/SteamLibrary/steamapps/common/Deadlock":"/data"
